theme: jekyll-theme-cayman
title: The American Political Landscape - Polarization between the Left and Right-wing
description: Bookmark this to keep an eye on my project updates!
--- layout: home background: 'https://github.com/ayarahmoun/ayarahmoun.github.io/blob/main/left_right.jpeg' ---
